In [1]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import linear_model
import numpy as np

In [2]:
df=pd.read_excel('Home_Price2.xlsx')
df

Area  Bedroom  Age   Price
0  2000      3.0   16  500000
1  2600      3.0   20  550000
2  3000      4.0   15  565000
3  3200      NaN   18  610000
4  3600      3.0   30  595000
5  4000      5.0    8  760000

In [3]:
import math  #for inserting in a empty block we will find the median of all the observations of given coloum to fill the data.
median_Bedroom=math.floor(df.Bedroom.median()) #for taking only integer value
median_Bedroom

3

In [4]:
df.Bedroom=df.Bedroom.fillna(median_Bedroom) # to update the table
df

Area  Bedroom  Age   Price
0  2000      3.0   16  500000
1  2600      3.0   20  550000
2  3000      4.0   15  565000
3  3200      3.0   18  610000
4  3600      3.0   30  595000
5  4000      5.0    8  760000

In [5]:
reg=linear_model.LinearRegression()
reg.fit(df[['Area','Bedroom','Age']],df.Price)  # inside 2d array independent variable and outside the dependent or target  

LinearRegression()

In [6]:
reg.coef_

array([   122.59764414, -22614.69311841,  -6821.14073156])

In [7]:
reg.intercept_

421495.6602603734

In [8]:
#when output depend on multiple varible we have equation: y=m1*x1+m2*x2+m3*x3+b
#where m1,m2,m3 are cofficients and b is intercept as calculated above

In [9]:
reg.predict([[3000,3,40]]) # to predict the price of a home having size of 3000  sq.ft ,having 3 bedroms and 40 years old 

array([448598.88406696])

In [10]:
#validating the answer
y=122.59764414*3000+(-22614.69311841)*3+(-6821.14073156)*40+421495.6602603734
print(y)

448598.8840627434


In [11]:
reg.predict([[2500,4,5]])  #size-2500 sq.ft Bedroom-4,Year-5

array([603425.29448233])